"""
database schema v1

Revision ID: 822d7cb712e7
Revises: 0507a5a16363
Create Date: 2022-10-04 18:16:43.190271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822d7cb712e7'
down_revision = '0507a5a16363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('zettels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('luhmann_identifier', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zettels')),
    sa.UniqueConstraint('luhmann_identifier', name=op.f('uq_zettels_luhmann_identifier')),
    sa.UniqueConstraint('title', name=op.f('uq_zettels_title'))
    )
    op.create_table('zettel_links_table',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('backlink_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backlink_id'], ['zettels.id'], name=op.f('fk_zettel_links_table_backlink_id_zettels')),
    sa.ForeignKeyConstraint(['link_id'], ['zettels.id'], name=op.f('fk_zettel_links_table_link_id_zettels')),
    sa.PrimaryKeyConstraint('link_id', 'backlink_id', name=op.f('pk_zettel_links_table'))
    )
    op.create_table('zettel_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zettel_id', sa.Integer(), nullable=True),
    sa.Column('transferred_to_zettelkasten', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['zettel_id'], ['zettels.id'], name=op.f('fk_zettel_updates_zettel_id_zettels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zettel_updates'))
    )
    op.create_table('updated_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zettel_update_id', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('old_column_value', sa.String(), nullable=False),
    sa.Column('new_column_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['zettel_update_id'], ['zettel_updates.id'], name=op.f('fk_updated_columns_zettel_update_id_zettel_updates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_updated_columns'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('updated_columns')
    op.drop_table('zettel_updates')
    op.drop_table('zettel_links_table')
    op.drop_table('zettels')
    op.drop_table('user')
    # ### end Alembic commands ###
