"""
empty message

Revision ID: 428f14252d38
Revises: ba2fcb4c6640
Create Date: 2022-12-30 14:11:26.063743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428f14252d38'
down_revision = 'ba2fcb4c6640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meditations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meditations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meditations')
    # ### end Alembic commands ###
