"""
empty message

Revision ID: 83621cc63ceb
Revises: 822d7cb712e7
Create Date: 2022-11-02 19:13:29.641175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83621cc63ceb'
down_revision = '822d7cb712e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=200), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.drop_column('user', 'password')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'email')
    op.drop_column('user', 'created_on')
    # ### end Alembic commands ###
