"""
empty message

Revision ID: ae793ea17598
Revises: b77b222cdd20
Create Date: 2022-11-07 11:15:50.899505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae793ea17598'
down_revision = 'b77b222cdd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_zettels_luhmann_identifier', 'zettels', type_='unique')
    op.drop_constraint('uq_zettels_title', 'zettels', type_='unique')
    op.create_index(op.f('ix_zettels_luhmann_identifier'), 'zettels', ['luhmann_identifier'], unique=True)
    op.create_index(op.f('ix_zettels_title'), 'zettels', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zettels_title'), table_name='zettels')
    op.drop_index(op.f('ix_zettels_luhmann_identifier'), table_name='zettels')
    op.create_unique_constraint('uq_zettels_title', 'zettels', ['title'])
    op.create_unique_constraint('uq_zettels_luhmann_identifier', 'zettels', ['luhmann_identifier'])
    # ### end Alembic commands ###
