"""
empty message

Revision ID: ba2fcb4c6640
Revises: 51e2980bd886
Create Date: 2022-12-30 01:22:22.230166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2fcb4c6640'
down_revision = '51e2980bd886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routines')
    # ### end Alembic commands ###
