"""
empty message

Revision ID: f724652d806f
Revises: ae793ea17598
Create Date: 2022-11-10 18:46:29.220558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f724652d806f'
down_revision = 'ae793ea17598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zettels', sa.Column('luhmann_id', sa.String(), nullable=False))
    op.drop_index('ix_zettels_luhmann_identifier', table_name='zettels')
    op.create_index(op.f('ix_zettels_luhmann_id'), 'zettels', ['luhmann_id'], unique=True)
    op.drop_column('zettels', 'luhmann_identifier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zettels', sa.Column('luhmann_identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_zettels_luhmann_id'), table_name='zettels')
    op.create_index('ix_zettels_luhmann_identifier', 'zettels', ['luhmann_identifier'], unique=False)
    op.drop_column('zettels', 'luhmann_id')
    # ### end Alembic commands ###
